name: Custom badge

on:
  push:
    branches:
      - main
      
jobs:
  badge_job:
    runs-on: ubuntu-latest
    steps:
      - id: date
        run: echo "##[set-output name=data;]$(date +"%Y+%m+%d")"
      - name: Time badge
        uses: RubbaBoy/BYOB@v1.3.0
        with:
          NAME: time
          ICON: 'git'
          LABEL: 'Updated at'
          STATUS: ${{ steps.date.outputs.data }}
          COLOR: 00EEFF
