name: Latest update

on:
  push:
    branches: 
      - main

jobs:
  get-date:
    runs-on: ubuntu-20.04
    outputs:
      output1: ${{ steps.step_one.outputs.date }}
    steps:
      - name: Set the date
        id: step_one
        run: |
          echo "date = $(date +"%Y+%m+%d")" >> $GITHUB_OUTPUT
          
#       - name: Use the date
#         id: step_two
#         run: |
#           echo "${{ env.date }}"
