name: Latest update

on:
  push:
    branches: 
      - main

jobs:
  get-date:
    runs-on: ubuntu-latest
    
    steps:
      - name: Set the date
        id: step_one
        run: |
          echo "date = $(date +"%Y+%m+%d")" >> $GITHUB_ENV
          
      - name: Use the date
        id: step_two
        run: |
          echo date
