name: Latest update

on:
  push:
    branches: 
      - main

jobs:
  get-date:
    runs-on: ubuntu-latest
    steps:
      - name: Set the date
        id: step_one
        run: |
          echo "date = $(date +"%Y+%m+%d")" >> $GITHUB_ENV
          
      - name: Use the date
        id: step_two
        run: |
          echo "${{ env.date }}"
   
  badge_job:
    runs-on: ubuntu-latest
    steps:
      - id: date
        run: echo "##[set-output name=data;]$(date +"%Y+%m+%d")"
      - name: Time badge
        uses: RubbaBoy/BYOB@v1.3.0
        with:
          NAME: time
          ICON: 'git'
          LABEL: 'Updated at'
          STATUS: ${{ steps.date.outputs.data }}
          COLOR: 00EEFF
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
